name: small_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.6.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  percent_indicator: ^4.2.3
  stroke_text: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "main_icon/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - main_icon/ic_launcher.png

  fonts:
    - family: cool
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf






